version: '3'
services:
  hg-money-transfer:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
      - ./data:/app/data
      - ./reports:/app/reports
    restart: always
